[package]
name = "ddns-updater"
description = "A simple RFC 2136 dynamic DNS updater"
repository = "https://github.com/chenxiaolong/ddns-updater"
readme = "README.md"
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
gethostname = "0.2.1"
log = "0.4.14"
rand = "0.8.4"
thiserror = "1.0.30"
toml = "0.5.8"

[dependencies.clap]
version = "3.0.0-rc.7"
features = ["derive"]

[dependencies.netif]
git = "https://github.com/bnoordhuis/netif.git"
rev = "9d5f620799f8e18175b3b255aed0646d02fda7d0"

[dependencies.serde]
version = "1.0.131"
features = ["derive"]

[dependencies.serde_with]
version = "1.11.0"
features = ["base64", "macros"]

[dependencies.trust-dns-client]
version = "0.21.0-alpha.4"
features = ["dnssec", "dnssec-ring"]
