[package]
name = "ddns-updater"
description = "A simple RFC 2136 dynamic DNS updater"
repository = "https://github.com/chenxiaolong/ddns-updater"
readme = "README.md"
license = "GPL-3.0"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
gethostname = "0.2.2"
log = "0.4.14"
netif = "0.1.1"
rand = "0.8.4"
thiserror = "1.0.30"
toml = "0.5.8"

[dependencies.clap]
version = "3.0.14"
features = ["derive"]

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.serde_with]
version = "1.11.0"
features = ["base64", "macros"]

[dependencies.trust-dns-client]
version = "0.21.0-alpha.4"
features = ["dnssec", "dnssec-ring"]
