[package]
name = "ddns-updater"
description = "A simple RFC 2136 dynamic DNS updater"
repository = "https://github.com/chenxiaolong/ddns-updater"
readme = "README.md"
license = "GPL-3.0"
version = "0.1.7"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.3"
gethostname = "0.4.0"
log = "0.4.17"
netif = "0.1.6"
rand = "0.8.5"
thiserror = "1.0.37"
toml = "0.5.9"

[dependencies.clap]
version = "4.0.26"
features = ["derive"]

[dependencies.serde]
version = "1.0.147"
features = ["derive"]

[dependencies.serde_with]
version = "2.1.0"
features = ["base64", "macros"]

[dependencies.trust-dns-client]
version = "0.22.0"
features = ["dnssec", "dnssec-ring"]
